name: HTB Speedrun Solve

on: [push, workflow_dispatch]

jobs:
  exploit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install pwntools

      - name: Run Exploit
        env:
          TERM: linux   # Curses xatosini butunlay yo'qotadi
          PWNLIB_NOTERM: 1 # Pwntools terminal xususiyatlarini o'chiradi
        run: python3 speedrun.py
